steps:
  - read: auto_publish
    from: args.auto_publish
    fallback:
      prompt: |
        Should the package be published automatically (when pushed to main branch with a version bump)?
        You MUST add a GitHub secret named NPM_TOKEN for this to work if you choose yes.
      choices:
        - yes
        - no: ''

  - if: auto_publish
    steps:
      - read: test_command
        from: args.test_command
        fallback:
          prompt: |
            What command should be run to test the package? Ideally, this command should check for sufficient
            coverage as well, since if it passes, the package will be published.
          default: npm test
  
      - read: lint_command
        from: args.lint_command
        fallback:
          prompt: |
            What command should be run to check code quality?
          default: echo "no linting command specified"

      - copy: workflow.yml
        to: ../.github/workflows/publish.yml
  